# Generated by Django 4.1.7 on 2023-03-03 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id', models.CharField(default=uuid.uuid1, max_length=261, unique=True)),
                ('animaltype', models.CharField(choices=[('dog', 'the one that barks'), ('cat', 'the one that meows'), ('lizard', 'the one that eats crickets'), ('snake', 'the one that slithers'), ('rabbit/bunny', 'the one that hops'), ('bird', 'the one that flaps'), ('fish', 'the one that swims'), ('frog', 'the one that croaks')], default='the one that barks', max_length=255)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('id', models.CharField(default=uuid.uuid1, max_length=261)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PetStory',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'PetStories',
            },
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id', models.CharField(default=uuid.uuid1, max_length=261, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, upload_to='')),
                ('pets', models.ManyToManyField(related_name='Owners', to='pet_profile.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_photos',
            field=models.ManyToManyField(related_name='pets', to='pet_profile.petphoto'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_stories',
            field=models.ManyToManyField(related_name='pets', to='pet_profile.petstory'),
        ),
    ]
