# Generated by Django 2.2 on 2023-11-16 00:53

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pet_species', models.CharField(choices=[('dog', 'the one that barks'), ('cat', 'the one that meows'), ('lizard', 'the one that eats crickets'), ('snake', 'the one that slithers'), ('rabbit', 'the one that hops'), ('bird', 'the one that flaps'), ('fish', 'the one that swims'), ('frog', 'the one that croaks'), ('plant', 'the one that breathes'), ('other', 'other')], default='the one that barks', max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('pet_photos', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=25, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'PetPhotos',
            },
        ),
        migrations.CreateModel(
            name='PetStory',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=25, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
                ('pets', models.ManyToManyField(to='pet_profile.Pet')),
            ],
            options={
                'verbose_name_plural': 'PetStories',
            },
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('slug', models.SlugField(blank=True, max_length=25)),
                ('age', models.PositiveIntegerField(null=True)),
                ('location', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, upload_to='')),
                ('id', models.CharField(default=uuid.UUID('1a7aa222-e980-41fc-9113-825c09979b1e'), max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('pets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owners', to='pet_profile.Pet')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
