# Generated by Django 4.1.7 on 2023-02-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('slug', models.SlugField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('slug', models.SlugField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PetStory',
            fields=[
                ('url', models.URLField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
                ('pet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pet_profile.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('url', models.URLField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_profile.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_profile.petowner'),
        ),
    ]
