# Generated by Django 2.2 on 2023-11-16 00:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='id',
            field=models.CharField(default=uuid.UUID('1733bc0a-aa08-47e2-972f-ae45e7e72c09'), max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
