# Generated by Django 4.1.7 on 2023-02-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animaltype',
            field=models.CharField(choices=[('the one that barks', 'dog'), ('the one that meows', 'cat'), ('the one that eats crickets', 'lizard'), ('the one that slithers', 'snake'), ('the one that hops', 'rabbit/bunny'), ('the one that flaps', 'bird'), ('the one that swims', 'fish'), ('the one that croaks', 'frog')], default='the one that barks', max_length=255),
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='petphoto',
            name='pet',
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='url',
            field=models.URLField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='petstory',
            name='pet',
        ),
        migrations.AlterField(
            model_name='petstory',
            name='url',
            field=models.URLField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ManyToManyField(to='pet_profile.petowner'),
        ),
        migrations.AddField(
            model_name='petphoto',
            name='pet',
            field=models.ManyToManyField(to='pet_profile.pet'),
        ),
        migrations.AddField(
            model_name='petstory',
            name='pet',
            field=models.ManyToManyField(to='pet_profile.pet'),
        ),
    ]
