# Generated by Django 2.2 on 2023-11-22 21:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0002_auto_20231115_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='id',
            field=models.CharField(default=uuid.UUID('1a8f7aff-2b2a-4526-8664-624ed5992054'), max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='pets',
        ),
        migrations.AddField(
            model_name='petowner',
            name='pets',
            field=models.ManyToManyField(blank=True, null=True, related_name='Owners', to='pet_profile.Pet'),
        ),
    ]
