# Generated by Django 4.2.5 on 2023-10-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0002_alter_pet_pet_photos_alter_pet_pet_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_photos',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_stories',
        ),
        migrations.AddField(
            model_name='petphoto',
            name='pets',
            field=models.ManyToManyField(to='pet_profile.pet'),
        ),
        migrations.AddField(
            model_name='petstory',
            name='pets',
            field=models.ManyToManyField(to='pet_profile.pet'),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
