# Generated by Django 4.1.7 on 2023-02-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0002_pet_animaltype_remove_pet_owner_alter_pet_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petstory',
            options={'verbose_name_plural': 'PetStories'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.AddField(
            model_name='petowner',
            name='pets',
            field=models.ManyToManyField(related_name='Owners', to='pet_profile.pet'),
        ),
    ]
