# Generated by Django 2.2 on 2023-10-28 19:45

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('pet_profile', '0003_remove_pet_pet_photos_remove_pet_pet_stories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petowner',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='petphoto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='petphoto',
            name='pets',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_profile.PetPhoto'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='password',
            field=models.CharField(default='hello', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petowner',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='username',
            field=models.CharField(default='username', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='animaltype',
            field=models.CharField(choices=[('dog', 'the one that barks'), ('cat', 'the one that meows'), ('lizard', 'the one that eats crickets'), ('snake', 'the one that slithers'), ('rabbit/bunny', 'the one that hops'), ('bird', 'the one that flaps'), ('fish', 'the one that swims'), ('frog', 'the one that croaks'), ('other', 'other')], default='the one that barks', max_length=255),
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='pets',
        ),
        migrations.AddField(
            model_name='petowner',
            name='pets',
            field=models.ForeignKey(default='mypet', on_delete=django.db.models.deletion.CASCADE, related_name='Owners', to='pet_profile.Pet'),
            preserve_default=False,
        ),
    ]
