# Generated by Django 4.1.7 on 2023-02-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0003_alter_petstory_options_remove_pet_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petowner',
            name='id',
            field=models.CharField(default='10101010', max_length=260),
        ),
    ]
