# Generated by Django 2.2 on 2023-11-24 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0003_auto_20231122_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='id',
            field=models.CharField(default=uuid.UUID('33c335f7-4564-4913-9e52-bb19850bf20d'), max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='pets',
            field=models.ManyToManyField(blank=True, related_name='Owners', to='pet_profile.Pet'),
        ),
    ]
