# Generated by Django 2.2 on 2023-10-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0004_auto_20231028_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
