# Generated by Django 4.1.7 on 2023-02-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0004_petowner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='id',
            field=models.CharField(default='10101010', max_length=261, unique=True),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='id',
            field=models.CharField(default='10101010', max_length=261, unique=True),
        ),
    ]
