# Generated by Django 2.2 on 2023-11-24 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0004_auto_20231124_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='id',
            field=models.CharField(default=uuid.UUID('ca529289-09d9-4943-ad69-c6346522f4df'), max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
