# Generated by Django 2.2 on 2023-10-28 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0005_auto_20231028_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='pets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owners', to='pet_profile.Pet'),
        ),
    ]
