# Generated by Django 4.1.7 on 2023-02-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0005_pet_id_alter_petowner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.CharField(default='10101010', max_length=261),
        ),
    ]
