# Generated by Django 2.2 on 2023-11-26 20:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0005_auto_20231124_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='id',
            field=models.CharField(default=uuid.UUID('aa21ccc5-a890-4298-935d-8a92cf08a507'), max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
