# Generated by Django 2.2 on 2023-10-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0006_auto_20231028_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='name',
        ),
    ]
