# Generated by Django 2.2 on 2023-10-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0007_remove_pet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petowner',
            name='name',
        ),
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default='my_pet', max_length=255),
            preserve_default=False,
        ),
    ]
