# Generated by Django 2.2 on 2023-10-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0008_auto_20231029_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petstory',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, primary_key=True, serialize=False),
        ),
    ]
