# Generated by Django 4.1.7 on 2023-02-25 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0008_alter_pet_id_alter_pet_slug_alter_petowner_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=261, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
