# Generated by Django 4.1.7 on 2023-02-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0009_alter_pet_id_alter_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.CharField(max_length=261),
        ),
    ]
