# Generated by Django 2.2 on 2023-11-11 20:50

import django.contrib.auth.models
from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0009_auto_20231029_0344'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='petowner',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='petowner',
            name='user_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default='User', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='slug',
            field=models.SlugField(blank=True, max_length=25),
        ),
    ]
