# Generated by Django 2.2 on 2024-02-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0010_auto_20231114_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_photos',
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='pets',
        ),
        migrations.AddField(
            model_name='petphoto',
            name='pets',
            field=models.ManyToManyField(to='pet_profile.Pet'),
        ),
    ]
