# Generated by Django 2.2 on 2024-02-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0010_auto_20231114_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='title',
            field=models.CharField(default='Sharik and Norwegian Forest', max_length=255),
        ),
    ]
