# Generated by Django 2.2 on 2023-11-12 22:20

from django.db import migrations, models
import hashid_field.field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0010_auto_20231111_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='animaltype',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_species',
            field=models.CharField(choices=[('dog', 'the one that barks'), ('cat', 'the one that meows'), ('lizard', 'the one that eats crickets'), ('snake', 'the one that slithers'), ('rabbit/bunny', 'the one that hops'), ('bird', 'the one that flaps'), ('fish', 'the one that swims'), ('frog', 'the one that croaks'), ('plantae', 'the one that breathes'), ('other', 'other')], default='the one that barks', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='user_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=uuid.UUID('29122d97-b63b-4dd9-be94-9834e385b5ae'), min_length=7, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
