# Generated by Django 4.1.7 on 2023-02-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0010_alter_pet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='id',
        ),
    ]
