# Generated by Django 4.1.7 on 2023-02-25 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0011_remove_pet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=261),
        ),
    ]
