# Generated by Django 2.2 on 2024-03-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0012_pet_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='profile_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
