# Generated by Django 2.2 on 2024-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0013_auto_20240311_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='profile_photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
