# Generated by Django 4.1.7 on 2023-02-28 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0014_pet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='porofile_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=261, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, primary_key=True, serialize=False),
        ),
    ]
