# Generated by Django 4.1.7 on 2023-03-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0015_pet_porofile_photo_alter_pet_id_alter_pet_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animaltype',
            field=models.CharField(choices=[('dog', 'the one that barks'), ('cat', 'the one that meows'), ('lizard', 'the one that eats crickets'), ('snake', 'the one that slithers'), ('rabbit/bunny', 'the one that hops'), ('bird', 'the one that flaps'), ('fish', 'the one that swims'), ('frog', 'the one that croaks')], default='the one that barks', max_length=255),
        ),
    ]
