# Generated by Django 2.2 on 2024-03-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0015_auto_20240318_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='animaltype',
        ),
    ]
